baseURL = "https://webvoke.ml"
disableLanguages = []
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "Webvoke"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 Webvoke.inc"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
name = "services"
url = "#services"
weight = 2
[[Languages.en.menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "blog"
url = "#blog"
weight = 6
[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 7

[params]
author = "Sneh Mehta"
description = "Webvoke inc"
google_analytics_id = "G-KSHBYKZD4H"
logo = "images/Mini-yellow-Logo.png"
post_share = true
typeformid = "u6nTL7" # Required
typeformuser = "myuser" # Optional
typeformwidth = "100%" # Optional
typeformheight = "800px" # Optional

[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAyepE5SyTZmonlwD6aOOt9sg4OZiHgouU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/ariel/animate.min.css"
[[params.plugins.css]]
link = "plugins/ariel/flaticon.css"
[[params.plugins.css]]
link = "plugins/ariel/fontawesome.min.css"
[[params.plugins.css]]
link = "plugins/ariel/owl.carousel.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[[params.plugins.js]]
link = "plugins/ariel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/ariel/html5shiv.min.js"
[[params.plugins.js]]
link = "plugins/ariel/jquery.countdown.min.js"
[[params.plugins.js]]
link = "plugins/ariel/lightcase.min.js"
[[params.plugins.js]]
link = "plugins/ariel/popper.min.js"
[[params.plugins.js]]
link = "plugins/ariel/respond.min.js"
[[params.plugins.js]]
link = "plugins/ariel/wow.min.js"
[params.preloader]
enable = false
preloader = "images/Mini-yellow-Logo.png"


[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"

